import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NevigationBar from "@/components/ui/menu/NevigationBar";
import "./globals.css";
import StoreProvider from '@/store/StoreProvider'

const poppins = Poppins({ weight:'400',preload: false });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en" className={poppins.className}>
        <body >
          <NevigationBar/>
          <div>
            {children}
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
